"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v_@c7+=b@ew0=p#mp%40!^5o&iu1$3_yaf#c)s_dok49ul72)2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'trans',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
]
# Справочник температурных поправок
TEMPERATURE_CORRECTIONS = {
    "700-709": {"correction": 0.897, "expansion_coefficient": 0.001263},
    "710-719": {"correction": 0.884, "expansion_coefficient": 0.001227},
    "720-729": {"correction": 0.870, "expansion_coefficient": 0.001193},
    "730-739": {"correction": 0.857, "expansion_coefficient": 0.001160},
    "740-749": {"correction": 0.844, "expansion_coefficient": 0.001128},
    "750-759": {"correction": 0.831, "expansion_coefficient": 0.001098},
    "760-769": {"correction": 0.818, "expansion_coefficient": 0.001068},
    "770-779": {"correction": 0.805, "expansion_coefficient": 0.001039},
    "780-789": {"correction": 0.792, "expansion_coefficient": 0.001010},
    "790-799": {"correction": 0.778, "expansion_coefficient": 0.000981},
    "800-809": {"correction": 0.765, "expansion_coefficient": 0.000953},
    "810-819": {"correction": 0.752, "expansion_coefficient": 0.000924},
    "820-829": {"correction": 0.725, "expansion_coefficient": 0.000896},
    "830-839": {"correction": 0.715, "expansion_coefficient": 0.000886},
    "840-849": {"correction": 0.712, "expansion_coefficient": 0.000841},
    "850-859": {"correction": 0.669, "expansion_coefficient": 0.000818},
    "860-869": {"correction": 0.686, "expansion_coefficient": 0.000793},
    "870-879": {"correction": 0.673, "expansion_coefficient": 0.000769},
    "880-889": {"correction": 0.660, "expansion_coefficient": 0.000746},
    "890-899": {"correction": 0.647, "expansion_coefficient": 0.000722},
    "900-909": {"correction": 0.638, "expansion_coefficient": 0.000699},
    "910-919": {"correction": 0.620, "expansion_coefficient": 0.000677},
    "920-929": {"correction": 0.607, "expansion_coefficient": 0.000655},
    "930-939": {"correction": 0.594, "expansion_coefficient": 0.000635},
    "940-949": {"correction": 0.581, "expansion_coefficient": 0.000615},
    "950-959": {"correction": 0.567, "expansion_coefficient": 0.000594},
    "960-969": {"correction": 0.554, "expansion_coefficient": 0.000575},
    "970-979": {"correction": 0.541, "expansion_coefficient": 0.000555},
    "980-989": {"correction": 0.528, "expansion_coefficient": 0.000536},
    "990-999": {"correction": 0.515, "expansion_coefficient": 0.000517},
    "1000-1009": {"correction": 0.502, "expansion_coefficient": 0.000499},
    "1010-1019": {"correction": 0.489, "expansion_coefficient": 0.000482},
    "1020-1029": {"correction": 0.476, "expansion_coefficient": 0.000464},
    "1030-1039": {"correction": 0.463, "expansion_coefficient": 0.000447},
    "1040-1049": {"correction": 0.450, "expansion_coefficient": 0.000441},
    "1050-1059": {"correction": 0.437, "expansion_coefficient": 0.000434},
    "1060-1069": {"correction": 0.424, "expansion_coefficient": 0.000398},
    "1070-1079": {"correction": 0.411, "expansion_coefficient": 0.000352},
}
ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
AUTH_USER_MODEL = 'trans.User'
LOGIN_URL = 'trans:login'  # Используйте namespace и имя URL-шаблона для страницы входа

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
